apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-quarkus
  namespace: mshaposh
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test1
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-quarkus-
      labels:
        build.appstudio.openshift.io/application: test1
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: mshaposh
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/private-quarkus-devfile-sample
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:mshaposh-java-quarkus-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:0b05a990917f20f82394d02f28841500df23e612
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-quarkus/$(tt.params.git-revision)
    status: {}
status: {}
